# Generated by Django 3.1.7 on 2021-04-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-added_on']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='added',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='todo_text',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='updated_on',
        ),
    ]
